Tighten diagnostic spacing when notes are missing
This omits the trailing border on the final snippet if no notes are present.

For example, originally we’d render:
```
error[E0499]: cannot borrow `v` as mutable more than once at a time
  ┌─ one_line.rs:3:5
  │
3 │     v.push(v.pop().unwrap());
  │     - first borrow later used by call
  │       ---- first mutable borrow occurs here
  │            ^ second mutable borrow occurs here
  │

error: aborting due to previous error
 = For more information about this error, try `rustc --explain E0499`.

```
…where as now we’ll render:
```
error[E0499]: cannot borrow `v` as mutable more than once at a time
  ┌─ one_line.rs:3:5
  │
3 │     v.push(v.pop().unwrap());
  │     - first borrow later used by call
  │       ---- first mutable borrow occurs here
  │            ^ second mutable borrow occurs here

error: aborting due to previous error
 = For more information about this error, try `rustc --explain E0499`.

```